trigger:
  - "*"

variables:
  pythonVersion: "3.7"

jobs:
  - job: Run
    pool:
      vmImage: "Ubuntu-16.04"

    container: "python:3.7"

    strategy:
      matrix:
        Tests:
          target: test
        Linting:
          target: lint

    steps:
      - script: |
          set -eux

          cd api-server
          sudo make develop
          make ${target}
