trigger:
  - "*"

variables:
  pythonVersion: "3.7"

jobs:
  - job: Run
    pool:
      vmImage: "Ubuntu-16.04"

    strategy:
      matrix:
        Tests:
          TARGET: test
        Linting:
          TARGET: lint

    steps:
      - script: |
          set -eux

          ./api-server/bin/test-utils/docker-run-tests
