# More information on gocd-flavor YAML can be found here:
# - https://github.com/tomzo/gocd-yaml-config-plugin#pipeline
# - https://www.notion.so/sentry/GoCD-New-Service-Quickstart-6d8db7a6964049b3b0e78b8a4b52e25d
format_version: 10
pipelines:
    deploy-release-registry:
        environment_variables:
            GCP_PROJECT: internal-sentry
            GKE_CLUSTER: zdpwkxst
            GKE_REGION: us-central1
            GKE_CLUSTER_ZONE: b
            GKE_BASTION_ZONE: b
        group: sentry-release-registry
        lock_behavior: unlockWhenFinished
        materials:
            release_registry_repo:
                git: git@github.com:getsentry/sentry-release-registry
                shallow_clone: true
                branch: master
                destination: sentry-release-registry
        stages:
            - checks:
                  fetch_materials: true
                  jobs:
                      checks:
                          environment_variables:
                              # Required for checkruns.
                              GITHUB_TOKEN: "{{SECRET:[devinfra-github][token]}}"
                          timeout: 1200
                          elastic_profile_id: sentry-release-registry
                          tasks:
                              - script: |
                                    /devinfra/scripts/checks/githubactions/checkruns.py \
                                    getsentry/sentry-release-registry \
                                    ${GO_REVISION_RELEASE_REGISTRY_REPO} \
                                    "main"
                              - script: |
                                    /devinfra/scripts/checks/googlecloud/checkcloudbuild.py \
                                    ${GO_REVISION_RELEASE_REGISTRY_REPO} \
                                    "sentryio" \
                                    "us-central1-docker.pkg.dev/sentryio/sentry-release-registry/image"
            - deploy:
                  approval:
                      type: success
                      allow_only_on_success: true
                  fetch_materials: true
                  jobs:
                      deploy:
                          timeout: 1200
                          elastic_profile_id: sentry-release-registry
                          tasks:
                              - script: |
                                    /devinfra/scripts/k8s/k8stunnel \
                                    && /devinfra/scripts/k8s/k8s-deploy.py \
                                    --label-selector="service=release-registry" \
                                    --image="us-central1-docker.pkg.dev/sentryio/sentry-release-registry/image:${GO_REVISION_RELEASE_REGISTRY_REPO}" \
                                    --container-name="release-registry"
